{{- if and (not .Values.existingSecret) .Values.config.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsdrop.fullname" . }}
  labels:
    {{- include "opsdrop.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.config.jwtSecret | b64enc | quote }}
{{- end }}
